fabrica/urls.py
# En tu archivo urls.py

from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('contactanos/', views.contactanos, name='contactanos'),
    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    path('listar_tareas/', views.lista_tareas, name='lista_tareas'),
    path('crear_estado/', views.crear_estado, name='crear_estado'),
    path('crear_tareas/', views.crear_tarea, name='crear_tarea'),
    path('tareas/modificar/<int:id>/', views.modificar_tarea, name='modificar_tarea'),
    path('tareas/eliminar/<int:id>', views.eliminar_tarea, name='eliminar_tarea'),
    path('crear_fabrica/', views.crear_fabrica, name='crear_fabrica'),
    path('crear_costurera/', views.crear_costurera, name='crear_costurera'),
    path('listar_costureras/', views.listar_costureras, name='listar_costureras'),
    path('modificar_costureras/<str:identificacion>/', views.modificar_costurera, name='modificar_costurera'),
    path('costureras/eliminar/<str:identificacion>', views.eliminar_costurera, name='eliminar_costurera')
    
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include("fabrica.urls"))
    
]

fabrica/models.py
from django.db import models



# Tabla costureras
class Costureras(models.Model):
    GENERO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otro'),
    ]
    identificacion = models.CharField(primary_key=True, max_length=50)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    direccion = models.CharField(max_length=200)
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES)

    def __str__(self):
        return self.nombre
    


# Tabla fabrica
class Fabrica(models.Model):
    nit = models.CharField(primary_key=True, max_length=50)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    costura = models.ForeignKey( Costureras, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.nombre  


# Tabla Estado, es el estado que va tener las tareas
class Estado(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

# Tabla Tareas
class Tareas(models.Model):
    descripcion = models.TextField()
    cant_prendas = models.IntegerField()
    fecha_ini = models.DateField()
    fecha_fin = models.DateField()
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    fabrica = models.ForeignKey(Fabrica, on_delete=models.CASCADE)
    costurera = models.ForeignKey(Costureras, on_delete=models.SET_NULL, null=True, blank=True)

templates/contactanos.html
{% extends "layouts/app.html" %}
{% load static %}

{% block title %}
Contactanos
{% endblock %}

{% block content %}
<div class="contactanos-container">
    <div class="form-container">
        <h2>Contactanos</h2>
        <form class="contact-form" action="{% url 'enviar_correo' %}" method="POST" autocomplete="off">
            {% csrf_token %}
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required><br>
            <label for="correo">Correo electrónico:</label>
            <input type="email" id="correo" name="correo" required><br>
            <label for="mensaje">Mensaje:</label>
            <textarea id="mensaje" name="mensaje" required></textarea><br>
            <button type="submit">Enviar</button>
        </form>
    </div>
    <div class="imagen-container">
        <img src="{% static 'imagen_contac.png' %}" alt="Imagen" class="moveUpDown">
    </div>
</div>
{% endblock %}

templates/crear_costurera.html
{% extends "layouts/app.html" %}
{% load static %}
{% block title %}Costurera{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Crear Costurera</h1>

    <form method="post" id="costurera-form" action="{% url 'crear_costurera' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

    <!-- Contenedor para los botones y centrado -->
    <div class="text-center mt-3">
        <!-- Botón para redirigir a listar_costureras.html -->
        <a href="{% url 'listar_costureras' %}" class="btn btn-secondary">Listar Costureras</a>
    </div>
</div>
{% endblock %}

templates/crear_estado.html
{% extends "layouts/app.html" %}
{% block title %}Crear estado{% endblock %}

{% block content %}
  <h2>Crear Estado</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

templates/crear_fabrica.html
{% extends "layouts/app.html" %}
{% load static %}
{% block title %}Fabrica{% endblock %}


{% block content %}
<div class="form-container">
    <h1>Crear Fábrica</h1>
    <form method="post" id="fabrica-form" action="{% url 'crear_fabrica' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

templates/crear_tarea.html
{% extends "layouts/app.html" %}
{% block title %}Tarea{% endblock %}


{% block content %}
<div class="form-container">
    <h1>Crear Tarea</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
        {% endblock %}

templates/detalle_tarea.html
<!-- En tu archivo detalle_tarea.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de Tarea</title>
</head>
<body>
    <h1>Detalle de Tarea</h1>
    <p><strong>Descripción:</strong> {{ tarea.descripcion }}</p>
    <p><strong>Cantidad de Prendas:</strong> {{ tarea.cant_prendas }}</p>
    <p><strong>Fecha de Inicio:</strong> {{ tarea.fecha_ini }}</p>
    <p><strong>Fecha de Fin:</strong> {{ tarea.fecha_fin }}</p>
   {% comment %}  {% if tarea.id_costurera %}
        <p><strong>Costurera Asignada:</strong> {{ tarea.costurera.nombre }} {{ tarea.costurera.apellido }}</p>
    {% else %}
        <p><strong>Costurera Asignada:</strong> Sin asignar</p>
        <a href="{% url 'asignar_tarea_costurera' tarea.id %}">Asignar a Costurera</a>
    {% endif %} {% endcomment %}
    <a href="{% url 'modificar_tarea' tarea.id %}">Modificar Tarea</a>
    <a href="{% url 'eliminar_tarea' tarea.id %}">Eliminar Tarea</a>
    <a href="{% url 'lista_tareas' %}">Volver a Lista de Tareas</a>
</body>
</html>

templates/eliminar_costurera.html
{% extends "layouts/app.html" %}

{% block title %}Eliminar Costurera{% endblock %}

{% block content %}
<div class="container">
    <h1>¿Estás seguro de que deseas eliminar a {{ costurera.nombre }} {{ costurera.apellido }}?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends "layouts/app.html" %}

{% block title %}
Portada
{% endblock %}

{% block content %}
{% load static %}

<header>

  <h1 class="title">Prototipo - Gestión de Tareas textil</h1>

</header>
<main>
  <div class="container">
    <section class="fabrica-section">
      <div class="fabrica-info-left">
        <h2>Problematica</h2>
        <p><br>
          En una fábrica textil, se presenta una problemática significativa relacionada con la asignación de tareas a
          sus
          costureras. Estas costureras son esenciales en el proceso de confección de prendas, pero la falta de un
          sistema
          eficiente de asignación de tareas está generando dificultades en la producción y tensiones en el equipo.
          Por ejemplo, consideremos el caso de una fábrica que necesita confeccionar una colección de camisas de alta
          demanda para la próxima temporada. Las costureras, responsables de coser las piezas de tela para ensamblar las
          camisas, enfrentan problemas para recibir instrucciones claras y específicas sobre cuántas camisas deben
          producir en cada turno y qué tipo de costuras o detalles deben priorizarse en cada una.
          Esta falta de claridad en la asignación de tareas provoca confusiones, retrasos en la producción y, en última
          instancia, afecta la calidad de las prendas. Algunas costureras pueden sentirse abrumadas por una carga de
          trabajo desigual, mientras que otras pueden tener períodos de inactividad, lo que conduce a un uso ineficiente
          de los recursos y a tensiones entre los miembros del equipo.
          Además, la falta de un sistema transparente y equitativo para asignar tareas puede generar resentimiento entre
          las costureras y la gerencia, lo que afecta negativamente el ambiente laboral y la motivación del personal.
          Es imperativo abordar esta problemática implementando un sistema de asignación de tareas más justo y
          eficiente,
          que garantice una distribución equitativa de la carga de trabajo y promueva una comunicación clara y abierta
          entre la gerencia y el equipo de costureras.
        </p><br> <br>
        <h2>Requisitos Funcionales</h2><br>
        <h3>Gestión de Tareas:</h3><br>
        <p>El sistema debe permitir a la fábrica crear, asignar, modificar y eliminar tareas para las costureras.
          Debe ser posible especificar la cantidad de prendas que se deben producir en cada tarea, así como los detalles
          específicos de la confección.</p><br>
        <h3>Asignación Tareas:</h3><br>

        <p>El sistema debe garantizar la asignación de tareas a las costureras</p>

        <p>Debe permitir descripción de las tareas para brindar instrucciones detalladas.</p><br>
        <h3>Seguimiento de Tareas y Progreso:</h3><br>
        <p>El sistema debe permitir realizar un seguimiento del progreso de cada tarea, incluyendo el estado actual y el
          tiempo
          estimado de finalización.</p>

        <p>Debe permitir descripción de las tareas para brindar instrucciones detalladas.</p>

      </div>
      <div class="fabrica-info-right">
        <img src="{% static 'fabrica.png' %}" alt="Imagen" class="moveUpDown"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <h2>Requisitos No Funcionales</h2><br>
        <h3>Acceso y Seguridad:</h3><br>
        <p>Debe haber diferentes niveles de acceso para garantizar que solo las personas autorizadas puedan crear,
          asignar o
          modificar tareas.(Fase 2)
        <p>La información confidencial, como los datos personales de las costureras o los detalles de diseño de las
          prendas, debe
          estar protegida y accesible solo para aquellos con los permisos adecuados. (Fase 2)</p><br>
        <h3>Flexibilidad y Adaptabilidad:</h3><br>
        <p>El sistema debe ser lo suficientemente flexible como para adaptarse a cambios en la demanda de producción,
          cambios en
          los recursos disponibles o cambios en las preferencias de diseño de las prendas.</p>
        <p>Debería permitir una fácil reasignación de tareas y ajustes en los plazos según sea necesario (Fase 2).</p>
        <br>


      </div>

    </section>
  </div>
</main>

{% endblock %}

templates/lista_tareas.html
{% extends "layouts/app.html" %}
{% block title %}Lista de tareas{% endblock %}

{% block content %}
<div class="container py-5">
  <h1 class="text-center mb-4">Listado de Tareas</h1>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for tarea in tareas %}
    <div class="col">
      <div class="card h-100 border border-primary">
        <div class="card-body">
          <h5 class="card-title">Tarea #{{ tarea.id }}</h5>
          <ul class="list-unstyled">
            <li><strong>Estado:</strong> {{ tarea.estado }}</li>
            <li><strong>Cantidad de prendas:</strong> {{ tarea.cant_prendas }}</li>
            <li><strong>Fecha de inicio:</strong> {{ tarea.fecha_ini }}</li>
            <li><strong>Fecha de fin:</strong> {{ tarea.fecha_fin }}</li>
            <li><strong>Costurera encargada:</strong> {{ tarea.costurera }}</li>
            <li><strong>Descripción de la tarea:</strong><br>{{ tarea.descripcion }}</li>
          </ul>
          <div class="text-center mt-3">
            <a href="{% url 'modificar_tarea' tarea.id %}" class="btn btn-primary me-2">Modificar</a>
            <a href="{% url 'eliminar_tarea' tarea.id %}" class="btn btn-danger">Eliminar</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/listar_costureras.html
{% extends "layouts/app.html" %}
{% load static %}
{% block title %}Listar Costureras{% endblock %}

{% block content %}
<div class="container">
    <h1>Listado de Costureras</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Identificación</th>
                <th>Nombre</th>
                <th>Eliminar</th>
                <th>Modificar Tarea</th>
            </tr>
        </thead>
        <tbody>
            {% for costurera in costureras %}
            <tr>
                <td>{{ costurera.identificacion }}</td>
                <td>{{ costurera.nombre }}</td>
                <td>
                    {% if costurera.tareas_set.all %}
                        <!-- Muestra el mensaje si la costurera tiene tareas asignadas -->
                        Costurera con tarea asignada
                    {% else %}
                        <!-- Botón para eliminar costurera si no está asignada a ninguna tarea -->
                        <form action="{% url 'eliminar_costurera' costurera.identificacion %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    {% endif %}
                </td>
                <td>
                    {% if costurera.tareas_set.all %}
                        <!-- Botón para ir a modificar tarea si está asignada a una tarea -->
                        <a href="{% url 'modificar_tarea' costurera.tareas_set.first.id %}" class="btn btn-primary">Modificar Tarea</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/login.html
{% extends "layouts/app.html" %}
{% block title %}login{% endblock %}

{% block content %}
  <h2>Iniciar Sesión</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Iniciar Sesión</button>
  </form>
{% endblock %}

templates/modificar_costurera.html
{% extends "layouts/app.html" %}
{% block title %}Modificar costurera{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Costurera: {{ costurera.nombre }} {{ costurera.apellido }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock %}

templates/modificar_tarea.html
{% extends "layouts/app.html" %}
{% block title %}Modificar tarea{% endblock %}


{% block content %}
<div class="form-container">
    <title>Modificar Tarea</title>
</head>
<body>
    <h1>Modificar Tarea</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
{% endblock %}